    def gitCommit() {
    sh "git rev-parse HEAD > GIT_COMMIT"
def gitCommit = readFile('GIT_COMMIT').trim()
    sh "rm -f GIT_COMMIT"
    return gitCommit
}

node {
    // Checkout source code from Git
    stage 'Checkout'
    checkout scm

    // Build Docker image
    stage 'Build'
    sh "docker build -t cd.example.com:50000/root/site-test:${gitCommit()} ."

    // Log in and push image to GitLab
    stage 'Publish'
    withCredentials(
        [[
            $class: 'UsernamePasswordMultiBinding',
            credentialsId: 'gitlab',
            passwordVariable: 'GITLAB_PASSWORD',
            usernameVariable: 'GITLAB_USERNAME'
        ]]
    ) {
        sh "docker login -u ${env.GITLAB_USERNAME} -p ${env.GITLAB_PASSWORD} cd.example.com:50000"
        sh "docker push cd.example.com:50000/root/site-test:${gitCommit()}"
    }


    // Deploy
    stage 'Deploy'

    marathon(
        url: 'http://marathon.mesos:8080',
        forceUpdate: false,
        filename: 'marathon.json',
        id: 'nginx',
        docker: "cd.example.com:50000/root/site-test:${gitCommit()}".toString()
    )
}
