apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-warp-cert
  labels:
    app: {{ template "cloudflare-warp-ingress.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  cert.pem: |-
    {{ .Values.cert }}
